### ISSUE TITLE
bzr seems to be able to create commits with no committers

### ISSUE THREAD

**Issue by termie** [termie/git-bzr-ng#10]
screws up git's fast-import :/

**Comment by termie** [comment]
actually it seems that it is due to commits with multiple authors, seems to be occurring even on recent versions of git

**Comment by mshuler** [comment]
yup.  http://paste.openstack.org/show/83/

looks like the import crash is from commit:

revno: 328 [merge]
author: mdietz mdietz@openstack, Cerberus matt.dietz@rackspace.com
committer: Tarmac
branch nick: trunk
timestamp: Tue 2010-10-05 20:13:50 +0000
message:
  Cleanup around the rackspace API for the ec2 to internal_id transition

## 

Michael

**Comment by mshuler** [comment]
partial success - needed to scribble before I forget  :)
https://bugs.launchpad.net/bzr-fastimport/+bug/496677

apt-get remove --purge bzr-fastimport
wget http://launchpadlibrarian.net/58059367/262_261.diff
mkdir -p ~/.bazaar/plugins ; cd ~/.bazaar/plugins
bzr branch lp:bzr-fastimport fastimport
cd fastimport
patch -p1 < ~/262_261.diff

then 'git bzr clone lp:nova' worked for me

**Comment by termie** [comment]
latest versions of bzr-fastimport / python-fastimport have corrected this, yay :)
