### ISSUE TITLE
Pushing back to local bzr repository causes argument error

### ISSUE THREAD

**Issue by matthew-brett** [termie/git-bzr-ng#11]
Thanks for doing this rewrite.  I was just testing with a version of my own test script (https://github.com/matthew-brett/git-bzr) and got an error pushing to bzr:

```
mkdir test-bzr
cd test-bzr
bzr init
echo 'text' > afile
bzr add afile
bzr commit -m 'A file'
# make git repo and import
cd ..
git bzr clone test-bzr test-git
cd test-git
# make a git commit and push
git co -b bzr-local bzr/master
echo 'more text' >> afile
git commit -am 'More text'
git bzr push ../test-bzr
```

This generates:

```
bzr: ERROR: extra argument to command fast-import: /home/mb312/tmp/tmp2/test-git/.git/bzr/repo/bzr-local
```

Is this expected?  (I'm hoping to be able to give up my own hacked git-bzr and use your script instead).

**Comment by termie** [comment]
going through this to check, there are a couple oddities with your test script, first off you are checking out bzr/master even though master is already based on bzr/master after your clone, second it seems like my git at least does not use 'co' for checkout.

I don't get your error, but I do get a different one: git bzr push apparently doesn't handle relative paths very well, so I'll fix that :)

**Comment by termie** [comment]
Relative path issue fixed in https://github.com/termie/git-bzr-ng/commit/2140b7e2ab24eefb1eaadb273f8ba69b083db64e
