### ISSUE TITLE
bzr-fastimport.patch - still required?

### ISSUE THREAD

**Issue by paulharris** [termie/git-bzr-ng#40]
Hi,

I see there is a bzr-fastimport.patch included with git-bzr-ng, but no further documentation.

It won't apply cleanly to the current bzr-fastimport trunk, especially the branch_updater.py bit.

Does it need to be fixed and applied?  Or is it not required anymore?

thanks,
Paul

**Comment by termie** [comment]
i don't have a working repro case for the bug it fixed, so at this point i'd say hopefully not required

**Comment by paulharris** [comment]
I tried it on a bunch of my repos at this end.  It wasn't able to do any bigger repos on windows, but I got it done on linux.
Without applying the patch.
