### ISSUE TITLE
error: Object êé³ì^äh¹fÍ"YÓñâ already has a mark

### ISSUE THREAD

**Issue by vasild** [termie/git-bzr-ng#5]
Hello,

during "git bzr push" I get this:

$ git bzr push
12:55:28 Calculating the revisions to include ...
12:55:29 Starting export of 66268 revisions ...
12:55:30 Exported 66268 revisions in 0:00:02
12:55:30 Starting import ...
error: Object êé³ì^äh¹fÍ"YÓñâ already has a mark
error: Object Ã    bÖ E.bÂÕq already has a mark
error: Object Jª¬
                 B|áõÁ already has a mark
error: Object ±`'m蟑zbl already has a mark
bzr: ERROR: exceptions.AttributeError: 'BTreeBuilder' object has no attribute '_find_ancestors'

What I have done before is to clone a bzr branch, for example foo, got branches foo and bzr/foo in git, then as new changes were made directly on the bzr branch, I did several times "git bzr sync bzr/foo" and "git merge bzr/foo" (while the current branch is foo). Now I have made a new commit in foo in git and want to push it back to the bzr repo, thus I tried "git bzr push" which emits the above error. Subsequent "git bzr push" result in "No new revisions to push."

Let me know if more details should be provided.

Thanks!

**Comment by termie** [comment]
Wow, that is quite a lot of revisions. Is the text I am seeing representing some unicode? I wonder whether perhaps a comparison somewhere is not unicode aware.

**Comment by vasild** [comment]
I think the text is just garbage, I get it printed in this garbage-like form in an utf-8 terminal.

**Comment by vasild** [comment]
Today I used a fresh "git bzr clone", committed in git and then "git bzr push" succeeded but emitted this:

$ git bzr push
14:18:49 Calculating the revisions to include ...
14:18:50 Starting export of 67424 revisions ...
14:18:51 Exported 67424 revisions in 0:00:02
14:18:58 Starting import ...
error: Object êé³ì^äh¹fÍ"YÓñâ already has a mark
error: Object Ã    bÖ E.bÂÕq already has a mark
error: Object Jª¬
                 B|áõÁ already has a mark
error: Object ±`'m蟑zbl already has a mark
14:19:01 Updating branch information ...
/usr/local/lib/python2.6/site-packages/Crypto/Util/randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken
  RandomPool_DeprecationWarning)
     branch master now has 3260 revisions and 0 tags
14:19:02 Updating the working tree for /usr/local/devel/mysql.git/mysql-trunk-innodb/.git/bzr/repo/master ...
All changes applied successfully.
14:19:08 Packing repository ...
| repacking chk:chk node 7819/4807794257425
\ repacking chk:chk node 160881/480779
14:31:51 Removing obsolete packs ...59
14:31:53 Imported 1 revision, updating 1 branch and 1 tree in 0:12:55
Generating post-push messageng stream:Done 10/10
Sending post-push message
Bundling 1 revision(s).
All changes applied successfully.
Pushed up to revision 3260.
$

So the printout of the garbage is not fatal. I think this bug bites when "git bzr sync" has been used several times before "git bzr push". I.e. when changes have been pulled from bzr a few times and pushed into bzr a few times.

**Comment by vasild** [comment]
Here is how to reproduce this (or another similar) bug:

mkdir /tmp/t
cd /tmp/t
mkdir b
cd b
bzr init
echo aa >> f
bzr add f
bzr commit -m 'add aa'
cd ..
mkdir g
cd g
git init
git bzr import ../b
git checkout b
echo bb >> f
git commit -a -m 'add bb'
git bzr push
cd ../b
echo cc >> f
bzr commit -m 'add cc'
cd ../g
git bzr sync
git merge bzr/b
cd ../b
echo dd >> f
bzr commit -m 'add dd'
cd ../g
git bzr sync
  # warning: Not updating refs/heads/bzr/b (new tip 330a987d8300ad7850f065214547fcd9e6fcf61e does not contain d4ad82136d16a05d79763a985fd699b871633010)
git log
git log bzr/b
  # notice the change has not been fetched
echo DD >> f
git commit -a -m 'add DD'
git bzr push

The last command gives me:
22:33:07 Calculating the revisions to include ...
22:33:07 Starting export of 4 revisions ...
22:33:07 Exported 4 revisions in 0:00:00
22:33:08 Starting import ...
bzr: ERROR: exceptions.AttributeError: 'BTreeBuilder' object has no attribute '_find_ancestors'

Traceback (most recent call last):
  File "/usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/commands.py", line 911, in exception_to_return_code
    return the_callable(_args, *_kwargs)
  File "/usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/commands.py", line 1111, in run_bzr
    ret = run(_run_argv)
  File "/usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/commands.py", line 689, in run_argv_aliases
    return self.run(__all_cmd_args)
  File "/usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/commands.py", line 704, in run
    return self._operation.run_simple(_args, *_kwargs)
  File "/usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/cleanup.py", line 135, in run_simple
    self.cleanups, self.func, *args, *_kwargs)
  File "/usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/cleanup.py", line 165, in _do_with_cleanups
    result = func(_args, *_kwargs)
  File "/usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/fastimport/__init__.py", line 384, in run
    params, verbose, user_map=user_map)
  File "/usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/fastimport/**init**.py", line 111, in _run
    return proc.process(p.iter_commands)
  File "/usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/fastimport/processor.py", line 95, in process
    self._process(command_iter)
  File "/usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/fastimport/processors/generic_processor.py", line 283, in _process
    processor.ImportProcessor._process(self, command_iter)
  File "/usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/fastimport/processor.py", line 117, in _process
    handler(self, cmd)
  File "/usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/fastimport/processors/generic_processor.py", line 493, in commit_handler
    handler.process()
  File "/usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/fastimport/processor.py", line 208, in process
    self.post_process_files()
  File "/usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/fastimport/bzr_commit_handler.py", line 607, in post_process_files
    self._get_inventories)
  File "/usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/fastimport/revision_store.py", line 374, in load_using_delta
    [(r,) for r in rev.parent_ids])
  File "/usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/groupcompress.py", line 1295, in get_known_graph_ancestry
    parent_map, missing_keys = self._index.find_ancestry(keys)
  File "/usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/groupcompress.py", line 2004, in find_ancestry
    return self._graph_index.find_ancestry(keys, 0)
  File "/usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/index.py", line 1519, in find_ancestry
    search_keys = index._find_ancestors(search_keys,
AttributeError: 'BTreeBuilder' object has no attribute '_find_ancestors'

bzr 2.3.0dev1 on python 2.6.5 (FreeBSD-8.0-STABLE-amd64-64bit-ELF)
arguments: ['/usr/home/vd-dev/bin/bzr-repo-install/bin/bzr', 'fast-import', '--import-marks=/tmp/t/g/.git/bzr/map/b-bzr', '--export-marks=/tmp/t/g/.git/bzr/map/b-bzr', '-', '/tmp/t/g/.git/bzr/repo/b']
encoding: 'US-ASCII', fsenc: 'US-ASCII', lang: None
plugins:
  bash_completion      /usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/plugins/bash_completion [2.3.0dev1]
  bzrtools             /usr/local/lib/python2.6/site-packages/bzrlib/plugins/bzrtools [2.1.0]
  extmerge             /usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/extmerge [unknown]
  fastimport           /usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/fastimport [0.9.0dev]
  git                  /usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/git [0.5.2dev]
  launchpad            /usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/plugins/launchpad [2.3.0dev1]
  mysql                /usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/mysql [0.4.2]
  netrc_credential_store /usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/plugins/netrc_credential_store [2.3.0dev1]
  news_merge           /usr/home/vd-dev/bin/bzr-repo-install/lib/python/bzrlib/plugins/news_merge [2.3.0dev1]
  svn                  /usr/home/vd-dev/.bazaar-dev/.bazaar/plugins/svn [1.0.3dev]

**\* Bazaar has encountered an internal error.  This probably indicates a
    bug in Bazaar.  You can help us fix it by filing a bug report at
        https://bugs.launchpad.net/bzr/+filebug
    including this traceback and a description of the problem.
No new revisions to push.

**Comment by vasild** [comment]
Above the formatter removed a newline before the commands "git log" and "echo DD >> f"

**Comment by termie** [comment]
This error message looks to be the _find_ancestors error, that is currently described in http://github.com/termie/git-bzr-ng/commit/f03d109c16761d171fdb2c229ae8e4ed629fb93a

Additionally the error related to the "new tip does not contain x" may be solved by using the --parent_branch option to git bzr push, ideally we could infer this but it requires a little bit of git-fu to figure out where a git branch likely branched from

**Comment by vasild** [comment]
Hello,

I think this bug has been fixed by the btree_index.patch. At least I have not seen it recently.

Thank you!
