### ISSUE TITLE
Cannot push branches with any changes to launchpad

### ISSUE THREAD

**Issue by MattDietz** [termie/git-bzr-ng#8]
Every time I branch in git, I can push the branch up so long as I don't make any changes first. However, if there's any kind of difference between my branch and master, it does this:

git bzr push lp:~cerberus/nova/api_tests
bzr: ERROR: exceptions.AttributeError: 'BTreeBuilder' object has no attribute '_find_ancestors'

Git version is 1.7.2.1
bzr is 2.2b4

**Comment by termie** [comment]
There is a workaround, it is described now in the README as of this commit: http://github.com/termie/git-bzr-ng/commit/f03d109c16761d171fdb2c229ae8e4ed629fb93a

Hopefully we can get this patch integrated into bzr somehow or change bzr-fastimport to get around it.
